### PR TITLE
[READY] Assign requirements to user

### PR DESCRIPTION
**Pull request by tarzan**
As a manager I want to be able to assign requirements to users.

### CODE REVIEW

**Comment by dkhgh** [comment]
I would use this mainly as a scope and still allow all users to add evidence for all requirements. So kindof like in this ugly wireframe:

screen shot 2015-10-27 at 20 07 35

**Comment by tarzan** [comment]
what we were struggling with is where to put the interface to assign requirements to users... Probably create a new view for that? We were thinking `user/1/user_requirements` showing the list of requirements and buttons with 'assign'. However, we already have a view showing all requirements.....

**Comment by dkhgh** [comment]
We could also create profiles and make an interface to to subscribe / assign profiles to users?

**Comment by alexanderjeurissen** [comment]
@DefactoSoftware/hackweek ready to review.

**Pull request merged**
